name: progo
channels:
  - fastchan
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - jupyterlab
  - autopep8
  - pip :
    - fastai==2.7.10
    - opencv-python
